Repository HewlettPackard/oneview-redfish-toolkit, pull requests merged in 2018-07, with the labels that each got.

#318 Fix sample curl command for session authentication
  README.md
Labels: task completed

#323 Fixing base uri for capabilities object
  oneview_redfish_toolkit/api/capabilities_object.py
  oneview_redfish_toolkit/mockups/redfish/CapabilitiesObject.json
Labels: composability support, task completed

#326 Updating CapabilitiesObject on Resource Zone
  CHANGELOG.md
  oneview_redfish_toolkit/api/zone.py
  oneview_redfish_toolkit/mockups/redfish/Zone.json
  oneview_redfish_toolkit/mockups/redfish/ZoneWithoutDrives.json
  oneview_redfish_toolkit/mockups/redfish/ZoneWithoutNetwork.json
Labels: composability support, in progress

#330 Fixing System Collection count issue
  CHANGELOG.md
  oneview_redfish_toolkit/api/computer_system_collection.py
Labels: in progress

#331 Implement ComputerSystem for a composed resource
  oneview_redfish_toolkit/api/computer_system.py
  oneview_redfish_toolkit/app.py
  oneview_redfish_toolkit/blueprints/computer_system.py
  oneview_redfish_toolkit/mockups/oneview/ServerProfile.json
  oneview_redfish_toolkit/mockups/redfish/ComputerSystem.json
  oneview_redfish_toolkit/tests/api/test_computer_system.py
  oneview_redfish_toolkit/tests/blueprints/test_computer_system.py
Labels: in progress

#336 Fixes endpoint to reset a server hardware of a System
  oneview_redfish_toolkit/blueprints/computer_system.py
  oneview_redfish_toolkit/tests/blueprints/test_computer_system.py
Labels: in progress

#338 Fix handling not found for server profile
  oneview_redfish_toolkit/blueprints/computer_system.py
  oneview_redfish_toolkit/tests/blueprints/test_computer_system.py
Labels: in progress

#344 Removing ExtendInfo from bad_request error
  oneview_redfish_toolkit/app.py
  oneview_redfish_toolkit/blueprints/computer_system.py
  oneview_redfish_toolkit/mockups/errors/InvalidJsonKey.json
Labels: task completed

#351 Composed System: Add ResourceBlocks in the Links
  oneview_redfish_toolkit/api/computer_system.py
  oneview_redfish_toolkit/blueprints/computer_system.py
  oneview_redfish_toolkit/mockups/oneview/ServerProfile.json
  oneview_redfish_toolkit/mockups/redfish/ComputerSystem.json
  oneview_redfish_toolkit/tests/api/test_computer_system.py
  oneview_redfish_toolkit/tests/blueprints/test_computer_system.py
Labels: composability support, in progress

#361 Allows create properly a Composed System without Storage
  oneview_redfish_toolkit/api/computer_system.py
  oneview_redfish_toolkit/blueprints/computer_system.py
  oneview_redfish_toolkit/tests/blueprints/test_create_computer_system.py
Labels: task completed

#358 Update Links in the Storage Resource Block
  oneview_redfish_toolkit/api/computer_system.py
  oneview_redfish_toolkit/api/storage_resource_block.py
  oneview_redfish_toolkit/api/zone.py
  oneview_redfish_toolkit/blueprints/resource_block.py
  oneview_redfish_toolkit/mockups/oneview/DriveIndexTrees.json
  oneview_redfish_toolkit/mockups/oneview/ServerProfileTemplates.json
  oneview_redfish_toolkit/mockups/redfish/StorageResourceBlock.json
  oneview_redfish_toolkit/tests/api/test_storage_resource_block.py
  oneview_redfish_toolkit/tests/blueprints/test_resource_block.py
Labels: composability support, in progress

#364 Resource Blocks in a Zone should list all Computer System Resource Blocks that could be used in a composition and not just "Unused" ones
  oneview_redfish_toolkit/api/zone.py
  oneview_redfish_toolkit/blueprints/zone.py
  oneview_redfish_toolkit/mockups/redfish/Zone.json
  oneview_redfish_toolkit/mockups/redfish/ZoneWithoutDrives.json
  oneview_redfish_toolkit/mockups/redfish/ZoneWithoutNetwork.json
  oneview_redfish_toolkit/tests/api/test_zone.py
  oneview_redfish_toolkit/tests/blueprints/test_zone.py
Labels: composability support, in progress

#374 Avoids http redirection when access URI without slash at end
  oneview_redfish_toolkit/app.py
  oneview_redfish_toolkit/tests/base_flask_test.py
  oneview_redfish_toolkit/tests/blueprints/test_create_computer_system.py
Labels: in progress

#372 Fixes Storage Resource Block to show Composed/unused status properly
  oneview_redfish_toolkit/api/storage_resource_block.py
  oneview_redfish_toolkit/tests/blueprints/test_resource_block.py
Labels: in progress
