Repository HewlettPackard/oneview-redfish-toolkit, pull requests merged in 2018-06, with the labels that each got.

#287 Check OneView availability
  CHANGELOG.md
  oneview_redfish_toolkit/api/scmb.py
  oneview_redfish_toolkit/tests/api/test_scmb.py
  oneview_redfish_toolkit/tests/base_test.py
  oneview_redfish_toolkit/tests/test_event_dispatcher.py
  oneview_redfish_toolkit/tests/test_util.py
  oneview_redfish_toolkit/util.py
Labels: in progress

#288 Updating installation package
  scripts/oneview-redfish-toolkit
  setup.cfg
  setup.py
Labels: task completed

#290 Remove duplicated code in blueprint tests
  oneview_redfish_toolkit/tests/base_flask_test.py
  oneview_redfish_toolkit/tests/blueprints/test_chassis.py
  oneview_redfish_toolkit/tests/blueprints/test_chassis_collection.py
  oneview_redfish_toolkit/tests/blueprints/test_composition_service.py
  oneview_redfish_toolkit/tests/blueprints/test_computer_system.py
  oneview_redfish_toolkit/tests/blueprints/test_computer_system_collection.py
  oneview_redfish_toolkit/tests/blueprints/test_event_service.py
  oneview_redfish_toolkit/tests/blueprints/test_manager.py
  oneview_redfish_toolkit/tests/blueprints/test_manager_collection.py
  oneview_redfish_toolkit/tests/blueprints/test_metadata.py
  oneview_redfish_toolkit/tests/blueprints/test_network_adapter.py
  oneview_redfish_toolkit/tests/blueprints/test_network_adapter_collection.py
  oneview_redfish_toolkit/tests/blueprints/test_network_device_function.py
  oneview_redfish_toolkit/tests/blueprints/test_network_device_function_collection.py
  oneview_redfish_toolkit/tests/blueprints/test_network_interface.py
  oneview_redfish_toolkit/tests/blueprints/test_network_interface_collection.py
  oneview_redfish_toolkit/tests/blueprints/test_network_port.py
  oneview_redfish_toolkit/tests/blueprints/test_network_port_collection.py
  oneview_redfish_toolkit/tests/blueprints/test_odata.py
  oneview_redfish_toolkit/tests/blueprints/test_redfish_base.py
  oneview_redfish_toolkit/tests/blueprints/test_resource_block_collection.py
  oneview_redfish_toolkit/tests/blueprints/test_service_root.py
  oneview_redfish_toolkit/tests/blueprints/test_session.py
  oneview_redfish_toolkit/tests/blueprints/test_storage.py
  oneview_redfish_toolkit/tests/blueprints/test_storage_collection.py
  oneview_redfish_toolkit/tests/blueprints/test_subscription.py
  oneview_redfish_toolkit/tests/blueprints/test_subscription_collection.py
  oneview_redfish_toolkit/tests/blueprints/test_thermal.py
  oneview_redfish_toolkit/tests/blueprints/test_zone_collection.py
Labels: enhancement, task completed

#303 Implement Storage ResourceBlock
  CHANGELOG.md
  oneview_redfish_toolkit/api/storage_resource_block.py
  oneview_redfish_toolkit/blueprints/resource_block.py
  oneview_redfish_toolkit/mockups/oneview/Drive.json
  oneview_redfish_toolkit/mockups/redfish/StorageResourceBlock.json
  oneview_redfish_toolkit/tests/api/test_storage_resource_block.py
  oneview_redfish_toolkit/tests/blueprints/test_resource_block.py
Labels: composability support, in progress

#314 Storage Resource Block Details (Storage and Drives)
  oneview_redfish_toolkit/api/storage_composition_details.py
  oneview_redfish_toolkit/api/storage_drive_composition_details.py
  oneview_redfish_toolkit/app.py
  oneview_redfish_toolkit/blueprints/storage_composition_details.py
  oneview_redfish_toolkit/conf/redfish.conf
  oneview_redfish_toolkit/mockups/oneview/Drive.json
  oneview_redfish_toolkit/mockups/oneview/DriveEnclosure.json
  oneview_redfish_toolkit/mockups/redfish/StorageCompositionDetails.json
  oneview_redfish_toolkit/mockups/redfish/StorageDriveCompositionDetails.json
  oneview_redfish_toolkit/mockups/redfish/StorageResourceBlock.json
  oneview_redfish_toolkit/tests/api/test_storage_composition_details.py
  oneview_redfish_toolkit/tests/api/test_storage_drive_composition_details.py
  oneview_redfish_toolkit/tests/blueprints/test_storage_composition_details.py
  redfish.conf
Labels: composability support, task completed

#320 Fix oslotest module version
  test-requirements.txt
  tox.ini
Labels: in progress
