Repository HewlettPackard/oneview-redfish-toolkit, pull requests merged in 2018-09, with the labels that each got.

#426 Use a label to save template_UUID instead of Description attribute in the server profile
  oneview_redfish_toolkit/api/computer_system.py
  oneview_redfish_toolkit/blueprints/computer_system.py
  oneview_redfish_toolkit/handler_multiple_oneview.py
  oneview_redfish_toolkit/mockups/oneview/LabelForServerProfile.json
  oneview_redfish_toolkit/services/computer_system_service.py
  oneview_redfish_toolkit/strategy_multiple_oneview.py
  oneview_redfish_toolkit/tests/api/test_computer_system.py
  oneview_redfish_toolkit/tests/blueprints/test_computer_system.py
Labels: in progress

#439 Fix unit tests for conf mode and client session tests
  oneview_redfish_toolkit/tests/base_flask_test.py
  oneview_redfish_toolkit/tests/blueprints/test_session.py
  oneview_redfish_toolkit/tests/test_client_session.py
Labels: task completed

#442 Feature/garbage collector for expired sessions
  oneview_redfish_toolkit/api/errors.py
  oneview_redfish_toolkit/app.py
  oneview_redfish_toolkit/client_session.py
  oneview_redfish_toolkit/tests/test_client_session.py
Labels: in progress

#446 Power off the server on compose/decompose request
  oneview_redfish_toolkit/api/computer_system.py
  oneview_redfish_toolkit/api/storage_resource_block.py
  oneview_redfish_toolkit/api/util/power_option.py
  oneview_redfish_toolkit/app.py
  oneview_redfish_toolkit/blueprints/computer_system.py
  oneview_redfish_toolkit/conf/redfish.conf
  oneview_redfish_toolkit/config.py
  oneview_redfish_toolkit/services/computer_system_service.py
  oneview_redfish_toolkit/tests/blueprints/test_computer_system.py
  oneview_redfish_toolkit/tests/blueprints/test_create_computer_system.py
Labels: in progress

#449 Fix threading lock
  oneview_redfish_toolkit/client_session.py
Labels: in progress

#450 Adds logs: info about how many OV and Redfish resources for Zone and Zone Collection
  oneview_redfish_toolkit/blueprints/zone.py
  oneview_redfish_toolkit/blueprints/zone_collection.py
  oneview_redfish_toolkit/services/logging_service.py
  oneview_redfish_toolkit/services/zone_service.py
Labels: in progress

#454 Feature/coverage
  .travis.yml
  README.md
  test-requirements.txt
  tox.ini
Labels: task completed

#452 Fixing debug performance logs for OneView calls with errors
  oneview_redfish_toolkit/multiple_oneview.py
Labels: in progress

#453 Update @Redfish.Copyright attribute adding 2018
  LICENSE
  oneview_redfish_toolkit/api/chassis_collection.py
  oneview_redfish_toolkit/api/errors.py
  oneview_redfish_toolkit/api/manager_collection.py
  oneview_redfish_toolkit/api/network_adapter_collection.py
  oneview_redfish_toolkit/api/network_device_function.py
  oneview_redfish_toolkit/api/network_device_function_collection.py
  oneview_redfish_toolkit/api/network_port.py
  oneview_redfish_toolkit/api/network_port_collection.py
  oneview_redfish_toolkit/api/service_root.py
  oneview_redfish_toolkit/api/subscription_collection.py
  oneview_redfish_toolkit/api/thermal.py
  oneview_redfish_toolkit/blueprints/manager.py
  oneview_redfish_toolkit/blueprints/metadata.py
  oneview_redfish_toolkit/blueprints/service_root.py
  oneview_redfish_toolkit/mockups/redfish/ServiceRoot.json
  oneview_redfish_toolkit/tests/api/test_blade_chassis.py
  oneview_redfish_toolkit/tests/api/test_blade_manager.py
  oneview_redfish_toolkit/tests/api/test_chassis_collection.py
  oneview_redfish_toolkit/tests/api/test_enclosure_chassis.py
  oneview_redfish_toolkit/tests/api/test_enclosure_manager.py
  oneview_redfish_toolkit/tests/api/test_manager_collection.py
  oneview_redfish_toolkit/tests/api/test_metadata.py
  oneview_redfish_toolkit/tests/api/test_network_adapter.py
  oneview_redfish_toolkit/tests/api/test_network_adapter_collection.py
  oneview_redfish_toolkit/tests/api/test_network_device_function.py
  oneview_redfish_toolkit/tests/api/test_network_device_function_collection.py
  oneview_redfish_toolkit/tests/api/test_network_port.py
  oneview_redfish_toolkit/tests/api/test_network_port_collection.py
  oneview_redfish_toolkit/tests/api/test_odata.py
  oneview_redfish_toolkit/tests/api/test_rack_chassis.py
  oneview_redfish_toolkit/tests/api/test_redfish_error.py
  oneview_redfish_toolkit/tests/api/test_redfish_json_validator.py
  oneview_redfish_toolkit/tests/api/test_service_root.py
  oneview_redfish_toolkit/tests/api/test_subscription.py
  oneview_redfish_toolkit/tests/api/test_subscription_collection.py
  oneview_redfish_toolkit/tests/api/test_thermal.py
  run.sh
  setup.py
Labels: in progress

#455 Freezes build dependencies
  requirements.txt
  test-requirements.txt
Labels: in progress

#451 Support for Delete Session (logout)
  oneview_redfish_toolkit/blueprints/session.py
  oneview_redfish_toolkit/client_session.py
  oneview_redfish_toolkit/tests/blueprints/test_session.py
Labels: in progress

#443 Update Managers collection and Manager
  oneview_redfish_toolkit/api/blade_chassis.py
  oneview_redfish_toolkit/api/blade_manager.py
  oneview_redfish_toolkit/api/computer_system.py
  oneview_redfish_toolkit/api/enclosure_chassis.py
  oneview_redfish_toolkit/api/enclosure_manager.py
  oneview_redfish_toolkit/api/manager.py
  oneview_redfish_toolkit/api/manager_collection.py
  oneview_redfish_toolkit/api/resource_block_computer_system.py
  oneview_redfish_toolkit/api/server_hardware_resource_block.py
  oneview_redfish_toolkit/api/status_mapping.py
  oneview_redfish_toolkit/app.py
  oneview_redfish_toolkit/blueprints/chassis.py
  oneview_redfish_toolkit/blueprints/computer_system.py
  oneview_redfish_toolkit/blueprints/manager.py
  oneview_redfish_toolkit/blueprints/manager_collection.py
  oneview_redfish_toolkit/blueprints/resource_block.py
  oneview_redfish_toolkit/client_session.py
  oneview_redfish_toolkit/handler_multiple_oneview.py
  oneview_redfish_toolkit/mockups/oneview/ApplianceHealthStatus.json
  oneview_redfish_toolkit/mockups/oneview/ApplianceNodeInfo.json
  oneview_redfish_toolkit/mockups/oneview/ApplianceState.json
  oneview_redfish_toolkit/mockups/redfish/BladeChassis.json
  oneview_redfish_toolkit/mockups/redfish/BladeManager.json
  oneview_redfish_toolkit/mockups/redfish/ComputerSystem.json
  oneview_redfish_toolkit/mockups/redfish/EnclosureChassis.json
  oneview_redfish_toolkit/mockups/redfish/EnclosureManager.json
  oneview_redfish_toolkit/mockups/redfish/Manager.json
  oneview_redfish_toolkit/mockups/redfish/ManagerCollection.json
  oneview_redfish_toolkit/mockups/redfish/ResourceBlockComputerSystem.json
  oneview_redfish_toolkit/multiple_oneview.py
  oneview_redfish_toolkit/services/manager_service.py
  oneview_redfish_toolkit/tests/api/test_blade_chassis.py
  oneview_redfish_toolkit/tests/api/test_blade_manager.py
  oneview_redfish_toolkit/tests/api/test_computer_system.py
  oneview_redfish_toolkit/tests/api/test_enclosure_chassis.py
  oneview_redfish_toolkit/tests/api/test_enclosure_manager.py
  oneview_redfish_toolkit/tests/api/test_manager.py
  oneview_redfish_toolkit/tests/api/test_manager_collection.py
  oneview_redfish_toolkit/tests/api/test_resource_block_computer_system.py
  oneview_redfish_toolkit/tests/blueprints/test_chassis.py
  oneview_redfish_toolkit/tests/blueprints/test_computer_system.py
  oneview_redfish_toolkit/tests/blueprints/test_manager.py
  oneview_redfish_toolkit/tests/blueprints/test_manager_collection.py
  oneview_redfish_toolkit/tests/blueprints/test_resource_block.py
  oneview_redfish_toolkit/tests/blueprints/test_session.py
  oneview_redfish_toolkit/tests/test_client_session.py
Labels: composability support, in progress

#457 Empty collections should not return error message
  oneview_redfish_toolkit/api/blade_chassis.py
  oneview_redfish_toolkit/api/computer_system.py
  oneview_redfish_toolkit/api/enclosure_chassis.py
  oneview_redfish_toolkit/api/resource_block_computer_system.py
  oneview_redfish_toolkit/app.py
  oneview_redfish_toolkit/blueprints/chassis_collection.py
  oneview_redfish_toolkit/blueprints/manager_collection.py
  oneview_redfish_toolkit/blueprints/network_adapter_collection.py
  oneview_redfish_toolkit/blueprints/network_device_function_collection.py
  oneview_redfish_toolkit/blueprints/network_port_collection.py
  oneview_redfish_toolkit/blueprints/subscription_collection.py
  oneview_redfish_toolkit/mockups/redfish/ChassisCollectionEmpty.json
  oneview_redfish_toolkit/mockups/redfish/ManagerCollectionEmpty.json
  oneview_redfish_toolkit/mockups/redfish/NetworkAdapterCollectionEmpty.json
  oneview_redfish_toolkit/mockups/redfish/NetworkDeviceFunctionCollectionEmpty.json
  oneview_redfish_toolkit/mockups/redfish/NetworkPortCollectionEmpty.json
  oneview_redfish_toolkit/services/manager_service.py
  oneview_redfish_toolkit/tests/blueprints/test_chassis_collection.py
  oneview_redfish_toolkit/tests/blueprints/test_manager_collection.py
  oneview_redfish_toolkit/tests/blueprints/test_network_adapter_collection.py
  oneview_redfish_toolkit/tests/blueprints/test_network_device_function_collection.py
  oneview_redfish_toolkit/tests/blueprints/test_network_port_collection.py
Labels: task completed

#460 Certificates directory on production installation for conf mode
  certs/.gitignore
  logging.conf
  oneview_redfish_toolkit/api/scmb.py
  oneview_redfish_toolkit/certs/.gitignore
  oneview_redfish_toolkit/certs/__init__.py
  oneview_redfish_toolkit/tests/api/test_scmb.py
  oneview_redfish_toolkit/tests/test_util.py
  scripts/oneview-redfish-toolkit
  setup.cfg
Labels: in progress

#461 Not found error should not return 500 on requests
  oneview_redfish_toolkit/api/network_device_function_collection.py
  oneview_redfish_toolkit/blueprints/chassis.py
  oneview_redfish_toolkit/blueprints/manager.py
  oneview_redfish_toolkit/mockups/redfish/NetworkDeviceFunctionCollection.json
  oneview_redfish_toolkit/tests/blueprints/test_chassis.py
  oneview_redfish_toolkit/tests/blueprints/test_manager.py
Labels: task completed

#463 Change order of scmb certs generation
  oneview_redfish_toolkit/api/scmb.py
  oneview_redfish_toolkit/app.py
  oneview_redfish_toolkit/tests/api/test_scmb.py
Labels: Event Service support, task completed
